[package]
name = "proxysette"
version = "0.1.0"
edition = "2021"
authors = ["Davide Paci <davidejose.paci@studenti.unitn.it>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id3 = "1.10.0"
zip = "0.6.6"