[tasks.build]
description = "Build the Rust application"
command = "cargo"
args = ["build", "--release"]

[tasks.copy_tools]
description = "Copy files to put into archive next to the compiled application"
script = '''
    mkdir target\release\tools
    cp -r /s tools\* target\release\tools\
    cp LICENSE.md target\release
    cp docs\USAGE.md target\release
'''

[tasks.package]
description = "Create a zip archive containing the compiled application and tools"
script = '''
    cd target\release
    zip -r proxysette.zip proxysette.exe tools LICENSE.md USAGE.md
'''

# Define the flow of tasks
[tasks.release-flow]
dependencies = ["build", "copy_tools", "package"]
