name: Release Workflow

on:
  push:
    branches:
      - main  # You can change this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest  # You can change the operating system as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out your repository's code

      - name: Setup Rust
        uses: actions/setup-rust@v1  # Set up Rust environment

      - name: Build the Rust application
        run: cargo build --release  # Run the cargo build command

      - name: Create tools directory and copy files
        run: |
          mkdir -p target/release/tools
          cp -r /s tools/* target/release/tools/
          cp LICENSE.md target/release
          cp docs/USAGE.md target/release

      - name: Create release zip archive
        run: |
          cd target/release
          zip -r proxysette.zip proxysette.exe tools LICENSE.md USAGE.md

      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: proxysette-release
          path: target/release/proxysette.zip
