name: Release Workflow

on:
  push:
    branches:
      - main  # You can change this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest  # You can change the operating system as needed

    steps:
      - name: Rust Release binary
        uses: rust-build/rust-build.action@v1.4.4
